services:
  app:
    image: atlars/tier-list:$IMAGE_TAG
    pull_policy: build
    build: .
    restart: unless-stopped
    environment:
      - NUXT_BROWSER_URL=http://chrome:9222
      - NUXT_PUBLIC_VERSION=$IMAGE_TAG
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tierlist.loadbalancer.server.port=3000"
    networks:
      - traefik
      - default
    depends_on:
      - chrome
  chrome:
    image: zenika/alpine-chrome:latest
    command: chromium-browser --headless --disable-gpu --no-sandbox --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
