name: Deploy to production
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add host key
        run: ssh-keyscan ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Establish port forwarding for Portainer
        run: ssh -fNv -o ExitOnForwardFailure=yes -L 9443:localhost:9443 ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}
      - name: Deploy app through Portainer
        uses: cssnr/portainer-stack-deploy-action@v1
        with:
          token: ${{ secrets.PORTAINER_TOKEN }}
          url: https://localhost:9443
          name: tier-list-prod
          standalone: true
          file: docker-compose.prod.yaml
          repo: https://github.com/atlars/tier-list
          ref: ${{ github.ref }}
          env_json: '{"IMAGE_TAG": "${{ github.ref_name }}"}'
